// src/ui/styles.js
export const styles = {
  page: {
    minHeight: "100vh",
    padding: "24px",
    background:
      "linear-gradient(180deg, rgba(238,242,255,1) 0%, rgba(255,255,255,1) 45%, rgba(250,250,250,1) 100%)",
    fontFamily:
      'ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, Helvetica, Arial, "Apple Color Emoji","Segoe UI Emoji"',
    color: "#111827",
  },
  container: { maxWidth: 1100, margin: "0 auto" },
  headerRow: {
    display: "flex",
    gap: 12,
    flexWrap: "wrap",
    alignItems: "flex-end",
    justifyContent: "space-between",
  },
  h1: { fontSize: 22, margin: 0, fontWeight: 800 },
  sub: { margin: "6px 0 0", fontSize: 14, color: "#4B5563" },
  badgeRow: { display: "flex", gap: 8, flexWrap: "wrap" },
  badge: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    fontSize: 12,
    padding: "6px 10px",
    borderRadius: 999,
    border: "1px solid #E5E7EB",
    background: "#F3F4F6",
    color: "#374151",
  },
  badgeAccent: {
    border: "1px solid #C7D2FE",
    background: "#EEF2FF",
    color: "#3730A3",
  },
  grid2: {
    marginTop: 18,
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 18,
    alignItems: "start",
  },
  phoneWrap: { display: "flex", justifyContent: "center" },
  phone: {
    position: "relative",
    width: 390,
    height: 844,
    borderRadius: 42,
    border: "1px solid #E5E7EB",
    background: "rgba(255,255,255,0.95)",
    boxShadow: "0 18px 50px rgba(17,24,39,0.12)",
    overflow: "hidden",
  },
  topBar: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 56,
    padding: "10px 14px",
    borderBottom: "1px solid #E5E7EB",
    background: "rgba(255,255,255,0.92)",
    backdropFilter: "blur(8px)",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  topTitle: { fontSize: 14, fontWeight: 800, margin: 0 },
  topMeta: { fontSize: 11, color: "#6B7280", marginTop: 2 },
  content: {
    position: "absolute",
    top: 56,
    bottom: 64,
    left: 0,
    right: 0,
    overflowY: "auto",
    padding: 14,
  },
  nav: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: 64,
    borderTop: "1px solid #E5E7EB",
    background: "rgba(255,255,255,0.92)",
    backdropFilter: "blur(8px)",
    display: "grid",
    gridTemplateColumns: "repeat(5, 1fr)",
    padding: "6px 6px",
  },
  navItem: {
    border: "none",
    background: "transparent",
    cursor: "pointer",
    padding: "6px 6px",
    borderRadius: 14,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 4,
    color: "#6B7280",
  },
  navItemActive: { color: "#4338CA" },

  sideCard: {
    borderRadius: 20,
    border: "1px solid #E5E7EB",
    background: "rgba(255,255,255,0.92)",
    backdropFilter: "blur(8px)",
    padding: 16,
    boxShadow: "0 8px 18px rgba(17,24,39,0.06)",
  },
  card: {
    borderRadius: 18,
    border: "1px solid #E5E7EB",
    background: "rgba(255,255,255,0.94)",
    padding: 14,
    boxShadow: "0 6px 14px rgba(17,24,39,0.06)",
  },
  cardTitleRow: { display: "flex", justifyContent: "space-between", gap: 10 },
  cardTitle: { fontSize: 13, fontWeight: 800, margin: 0 },
  small: { fontSize: 12, color: "#4B5563" },

  btnPrimary: {
    width: "100%",
    border: "none",
    borderRadius: 14,
    padding: "12px 14px",
    background: "#4F46E5",
    color: "white",
    fontWeight: 800,
    fontSize: 13,
    cursor: "pointer",
    boxShadow: "0 10px 18px rgba(79,70,229,0.22)",
  },
  btnSecondary: {
    width: "100%",
    borderRadius: 14,
    padding: "12px 14px",
    background: "white",
    color: "#111827",
    fontWeight: 800,
    fontSize: 13,
    cursor: "pointer",
    border: "1px solid #E5E7EB",
  },
  btnSmall: {
    borderRadius: 12,
    padding: "8px 10px",
    background: "white",
    color: "#111827",
    fontWeight: 800,
    fontSize: 12,
    cursor: "pointer",
    border: "1px solid #E5E7EB",
  },

  chip: {
    borderRadius: 999,
    padding: "6px 10px",
    fontSize: 12,
    border: "1px solid #E5E7EB",
    background: "white",
    cursor: "pointer",
  },
  chipOn: { border: "1px solid #4F46E5", background: "#EEF2FF", color: "#3730A3" },

  bubbleLeft: {
    maxWidth: "78%",
    borderRadius: 16,
    padding: "8px 10px",
    border: "1px solid #E5E7EB",
    background: "white",
    fontSize: 13,
    lineHeight: 1.25,
  },
  bubbleRight: {
    maxWidth: "78%",
    borderRadius: 16,
    padding: "8px 10px",
    border: "1px solid #4F46E5",
    background: "#4F46E5",
    color: "white",
    fontSize: 13,
    lineHeight: 1.25,
  },
  textarea: {
    width: "100%",
    borderRadius: 14,
    border: "1px solid #E5E7EB",
    padding: 10,
    fontSize: 13,
    outline: "none",
    resize: "vertical",
  },
};
